### ISSUE TITLE
ERROR: denied: permission_denied: write_package

### ISSUE THREAD

**Issue by koriym** [koriym/asd-action#15]
https://github.com/alps-asd/app-state-diagram/actions/runs/7135212304/job/19431531809

上記のように `Error: buildx failed with: ERROR: denied: permission_denied: write_package`エラーが発生。app-state-diagramパッケージも同様のエラーがでたがRoleをwriteにしたことで解消した。asd-actionは解消しない。writeにしても変化なし。(???)

<img width="1293" alt="image" src="https://github.com/alps-asd/asd-action/assets/529021/6cac1254-fbba-4f48-8b3f-dfde4c09ea08">

**Comment by NaokiTsuchiya** [comment]
<img width="1046" alt="image" src="https://github.com/alps-asd/asd-action/assets/17171732/9b8483d7-356c-4e0b-9ed7-46782489db45">

`app-state-diagram` のリポジトリに write 権限を付与して解決しました。
