### ISSUE TITLE
ビルド済みのイメージを利用するようにする

### ISSUE THREAD

**Issue by NaokiTsuchiya** [koriym/asd-action#4]
現在は、以下のように `asd-action` 実行時に docker image が 都度 build されます。

![image](https://user-images.githubusercontent.com/17171732/142204191-99466aa1-0d42-4f14-a024-0ee6e5933999.png)

https://github.com/psalm/psalm-github-security-scan のようにビルド済みのコンテナを実行する形式にすることで、都度ビルド実行されず、ビルドされたイメージを利用するだけになります。

**Comment by koriym** [comment]
リリース優先したやり残しです！そのpsalmの良さそうですね。
